# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e17713078f1a1457c3d0e499672378f2c192fa1c8bb1278e2450d89efe30bcfddea74306b4c343793d54070b1670d073ce72a29fc2114270260760be8eb2ac7

test:
  secret_key_base: 09478f9da1ebdd5ed0c961430ddbe6ce2184b6581477cc3fe6d47247ced4205208941e6084a8038c0ea6d0afbae860f934f883257860af6ae47d2e7fb83eedc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
